Repository Turbo87/flight-recorder-manufacturers, pull requests merged in 2021-04, with the labels that each got.

#57 Added 8 more FAI-approved GPS manufacturers
  manufacturers.json
Labels: enhancement

#59 Replace TravisCI with GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#65 Drop support for Node 10 and below
  .github/workflows/ci.yml
  package.json
Labels: breaking
